#cloud-config
package_update: true
packages:
  - openjdk-17-jdk
  - git
  - maven
  - nodejs
  - npm
runcmd:
  - git clone https://github.com/Panos994/Order-Dashboard-System.git /opt/Order-Dashboard-System
  - cd /opt/Order-Dashboard-System/backend && mvn clean package
  - java -jar /opt/Order-Dashboard-System/backend/target/*.jar &
  # Αν θέλεις build το frontend
  - cd /opt/Order-Dashboard-System/frontend && npm install && npm run build
  # Αν θέλεις serve με nginx θα χρειαστεί κι άλλο step