#cloud-config
package_update: true
packages:
  - git
  - openjdk-17-jdk
  - maven

runcmd:
  - git clone https://github.com/Panos994/Order-Dashboard-System.git /opt/order-dashboard
  - cd /opt/order-dashboard/backend && mvn clean package -DskipTests
  - |
    cat <<EOF > /etc/systemd/system/orderdashboard.service
    [Unit]
    Description=Order Dashboard Spring Boot
    After=network.target

    [Service]
    User=root
    WorkingDirectory=/opt/order-dashboard/backend
    ExecStart=/usr/bin/java -jar /opt/order-dashboard/backend/target/*.jar
    SuccessExitStatus=143
    Restart=always
    RestartSec=10

    [Install]
    WantedBy=multi-user.target
    EOF
  - systemctl daemon-reload
  - systemctl enable orderdashboard
  - systemctl start orderdashboard