#cloud-config
package_update: true
packages:
  - postgresql
runcmd:
  - sudo -u postgres psql -c "CREATE ROLE dbuser WITH LOGIN PASSWORD 'pass123';"
  - sudo -u postgres psql -c "CREATE DATABASE order_system_db OWNER dbuser;"
  - sudo -u postgres psql -c "ALTER ROLE dbuser CREATEDB;"
  - sudo sed -i "s/^#listen_addresses =.*/listen_addresses = '*'/g" /etc/postgresql/*/main/postgresql.conf
  - echo "host all all 10.0.0.0/24 md5" | sudo tee -a /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql