#cloud-config
package_update: true
packages:
  - git
  - nodejs
  - npm
  - nginx

runcmd:
  - git clone https://github.com/Panos994/Order-Dashboard-System.git /opt/order-dashboard
  - cd /opt/order-dashboard/frontend && npm install && npm run build
  - rm -rf /var/www/html/*
  - cp -r /opt/order-dashboard/frontend/dist/* /var/www/html/
  - systemctl enable nginx
  - systemctl restart nginx